/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.32                          *
 *        Compiled Oct  8 2015, 11:59:02                              *
 *        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
#include <GUI/WM_MyDefines.h>
#include <Modules/datalogger.h>
#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_TREEVIEW_0 (GUI_ID_USER + 0x03)
#define ID_TEXT_0 (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
extern osSemaphoreId DR_Semaphore;
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { FRAMEWIN_CreateIndirect, "Choose file", ID_FRAMEWIN_0, 30, 40, 180, 240, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Open", ID_BUTTON_0, 95, 177, 60, 24, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Cancel", ID_BUTTON_1, 13, 178, 60, 24, 0, 0x0, 0 },
    { TREEVIEW_CreateIndirect, "Treeview", ID_TREEVIEW_0, 11, 20, 148, 148, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "USB Flash Drive:", ID_TEXT_0, 12, 4, 96, 16, 0, 0x0, 0 },
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN                hItem;
  int                    NCode;
  int                    Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
      //
      // Initialization of 'Treeview'
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TREEVIEW_0);
      // USER START (Optionally insert additional code for further widget initialization)
      hTreeView = hItem;
      // USER END
      break;
    case WM_NOTIFY_PARENT:
      Id    = WM_GetId(pMsg->hWinSrc);
      NCode = pMsg->Data.v;
      switch(Id) {
        case ID_BUTTON_0: // Notifications sent by 'Open'
          switch(NCode) {
            case WM_NOTIFICATION_CLICKED:
              // USER START (Optionally insert code for reacting on notification message)
              // USER END
              break;
            case WM_NOTIFICATION_RELEASED:
              // USER START (Optionally insert code for reacting on notification message)

              TREEVIEW_ITEM_GetText(TREEVIEW_GetSel(hTreeView), (uint8_t*)DR.filename ,sizeof(DR.filename));
              TEXT_SetText(hFileName, DR.filename);

              TREEVIEW_ITEM_Delete(hMainDir);
              GUI_EndDialog(hChooseFile,0);
              WM_EnableWindow(hMW);
              WM_EnableWindow(hMpage);
              hChooseFile = 0;
              // USER END
              break;
              // USER START (Optionally insert additional code for further notification handling)
              // USER END
          }
          break;
            case ID_BUTTON_1: // Notifications sent by 'Cancel'
              switch(NCode) {
                case WM_NOTIFICATION_CLICKED:
                  // USER START (Optionally insert code for reacting on notification message)
                  // USER END
                  break;
                case WM_NOTIFICATION_RELEASED:
                  // USER START (Optionally insert code for reacting on notification message)
                  TREEVIEW_ITEM_Delete(hMainDir);
                  GUI_EndDialog(hChooseFile,0);
                  WM_EnableWindow(hMW);
                  WM_EnableWindow(hMpage);
                  hChooseFile = 0;
                  // USER END
                  break;
                  // USER START (Optionally insert additional code for further notification handling)
                  // USER END
              }
              break;
                case ID_TREEVIEW_0: // Notifications sent by 'Treeview'
                  switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                      // USER START (Optionally insert code for reacting on notification message)
                      // USER END
                      break;
                    case WM_NOTIFICATION_RELEASED:
                      // USER START (Optionally insert code for reacting on notification message)
                      // USER END
                      break;
                    case WM_NOTIFICATION_MOVED_OUT:
                      // USER START (Optionally insert code for reacting on notification message)
                      // USER END
                      break;
                    case WM_NOTIFICATION_SEL_CHANGED:
                      // USER START (Optionally insert code for reacting on notification message)
                      // USER END
                      break;
                      // USER START (Optionally insert additional code for further notification handling)
                      // USER END
                  }
                  break;
                  // USER START (Optionally insert additional code for further Ids)
                  // USER END
      }
      break;
      // USER START (Optionally insert additional message handling)
      // USER END
        default:
          WM_DefaultProc(pMsg);
          break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateChoose file
 */
WM_HWIN CreateChooseFile(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
