/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.32                          *
 *        Compiled Oct  8 2015, 11:59:02                              *
 *        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
#include <GUI/WM_MyDefines.h>
#include <Modules/datalogger.h>
#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_1    (GUI_ID_USER + 0x01)
#define ID_BUTTON_0    (GUI_ID_USER + 0x02)
#define ID_TEXT_0    (GUI_ID_USER + 0x03)
#define ID_TEXT_1    (GUI_ID_USER + 0x04)
#define ID_TEXT_2    (GUI_ID_USER + 0x05)
#define ID_TEXT_3    (GUI_ID_USER + 0x06)
#define ID_TEXT_4    (GUI_ID_USER + 0x07)
#define ID_DROPDOWN_0    (GUI_ID_USER + 0x08)
#define ID_TEXT_5    (GUI_ID_USER + 0x09)
#define ID_TEXT_6    (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
extern osSemaphoreId DR_Semaphore;
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { WINDOW_CreateIndirect, "Impedances", ID_WINDOW_0, 0, 0, 222, 270, 0, 0x0, 0 },
//    { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 12, 75, 200, 132, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Open file", ID_BUTTON_0, 130, 22, 80, 24, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Calculate", ID_BUTTON_1, 130, 72, 80, 24, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text1", ID_TEXT_0, 14, 13, 84, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text4", ID_TEXT_1, 14, 54, 52, 17, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text6", ID_TEXT_2, 14, 154, 210, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text7", ID_TEXT_6, 14, 234, 210, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text3", ID_TEXT_3, 14, 112, 178, 17, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text5", ID_TEXT_5, 14, 200, 80, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text2", ID_TEXT_4, 14, 30, 100, 20, 0, 0x64, 0 },
    { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 14, 74, 80, 21, 0, 0x0, 0 },
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
      //
      // Initialization of 'Impedances'
      //
      hItem = pMsg->hWin;
      WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
      //
      // Initialization of 'Text1'
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
      TEXT_SetText(hItem, "File:");
      //
      // Initialization of 'Text2'
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
      TEXT_SetFont(hItem, GUI_FONT_16B_1);
      TEXT_SetText(hItem, "no file selected");
      hFileName = hItem;
      //
      // Initialization of 'Text3'
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
      TEXT_SetText(hItem, "Source impedance:");
      //
      // Initialization of 'Text6'
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
      TEXT_SetFont(hItem, GUI_FONT_20B_1);
      TEXT_SetText(hItem, "0.00 + 0.00i Ohm");
      hText_ZS = hItem;
      //
      // Initialization of 'Text5'
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
      TEXT_SetText(hItem, "Load impedance:");
      //
      // Initialization of 'Text7'
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
      TEXT_SetFont(hItem, GUI_FONT_20B_1);
      TEXT_SetText(hItem, "0.00 + 0.00i Ohm");
      hText_ZL = hItem;
      //
      // Initialization of 'Text4'
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
      TEXT_SetText(hItem, "Harmonic:");
      //
      // Initialization of 'Dropdown'
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
      DROPDOWN_SetFont(hItem, GUI_FONT_16B_1);
      DROPDOWN_SetListHeight(hItem, 96 + 2);
      DROPDOWN_AddString(hItem, "DC");
      DROPDOWN_AddString(hItem, "50Hz");
      DROPDOWN_AddString(hItem, "100Hz");
      DROPDOWN_AddString(hItem, "150Hz");
      DROPDOWN_AddString(hItem, "200Hz");
      DROPDOWN_AddString(hItem, "250Hz");
      DROPDOWN_AddString(hItem, "300Hz");
      DROPDOWN_AddString(hItem, "350Hz");
      DROPDOWN_AddString(hItem, "400Hz");
      DROPDOWN_AddString(hItem, "450Hz");
      DROPDOWN_AddString(hItem, "500Hz");
      DROPDOWN_AddString(hItem, "550Hz");
      DROPDOWN_AddString(hItem, "600Hz");
      DROPDOWN_AddString(hItem, "650Hz");
      DROPDOWN_AddString(hItem, "700Hz");
      DROPDOWN_AddString(hItem, "750Hz");
      DROPDOWN_AddString(hItem, "800Hz");
      DROPDOWN_SetAutoScroll(hItem, 1);
      DROPDOWN_SetScrollbarWidth(hItem, 20);
      DROPDOWN_SetSel(hItem, 1);
      Zf_idx = 1;
      hDd_Zf = hItem;
      // USER START (Optionally insert additional code for further widget initialization)
      // USER END
      break;
    case WM_NOTIFY_PARENT:
      Id    = WM_GetId(pMsg->hWinSrc);
      NCode = pMsg->Data.v;
      switch(Id) {
        case ID_BUTTON_0: // Notifications sent by 'Open file'
          switch(NCode) {
            case WM_NOTIFICATION_CLICKED:
              // USER START (Optionally insert code for reacting on notification message)
              // USER END
              break;
            case WM_NOTIFICATION_RELEASED:
              // USER START (Optionally insert code for reacting on notification message)
              if(hChooseFile == 0 && USB.disk_connected)
              {
                if(DR_ScanFilesOnDisk() == FR_OK)
                {
                  hChooseFile = CreateChooseFile();
                  hMainDir = TREEVIEW_ITEM_Create(TREEVIEW_ITEM_TYPE_NODE, "PGM", 0);
                  TREEVIEW_AttachItem(hTreeView, hMainDir, 0, 0);

                  for(uint8_t i = DR.files_count; i > 0; i--)
                  {
                    TREEVIEW_ITEM_Handle hTreeItemNew = TREEVIEW_ITEM_Create(TREEVIEW_ITEM_TYPE_LEAF, DR.LOG_files[i-1].fname, i-1);
                    TREEVIEW_AttachItem(hTreeView, hTreeItemNew, hMainDir, TREEVIEW_INSERT_FIRST_CHILD);
                  }

                  TREEVIEW_SetAutoScrollV(hTreeView, 1);
                  TREEVIEW_ITEM_Expand(hMainDir);
                  WM_DisableWindow(hMW);
                  WM_DisableWindow(hMpage);
                }
              }
              // USER END
              break;
              // USER START (Optionally insert additional code for further notification handling)
              // USER END
          }
          break;
          case ID_BUTTON_1: // Notifications sent by 'Calculate'
            switch(NCode) {
              case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
              case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                if(USB.disk_connected)
                {
					/* Start calculation of impedance by releasing DR_Thread */
					osSemaphoreRelease(DR_Semaphore);
                }
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
          break;
            case ID_DROPDOWN_0: // Notifications sent by 'Dropdown'
              switch(NCode) {
                case WM_NOTIFICATION_CLICKED:
                  // USER START (Optionally insert code for reacting on notification message)
                  // USER END
                  break;
                case WM_NOTIFICATION_RELEASED:
                  // USER START (Optionally insert code for reacting on notification message)
                  // USER END
                  break;
                case WM_NOTIFICATION_SEL_CHANGED:
                  // USER START (Optionally insert code for reacting on notification message)
                  Zf_idx = (uint8_t)DROPDOWN_GetSel(hDd_Zf);
                  // USER END
                  break;
                  // USER START (Optionally insert additional code for further notification handling)
                  // USER END
              }
              break;
              // USER START (Optionally insert additional code for further Ids)
              // USER END
      }
      break;
      // USER START (Optionally insert additional message handling)
      // USER END
        default:
          WM_DefaultProc(pMsg);
          break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateImpedances
 */
WM_HWIN CreateImpedances(void);
WM_HWIN CreateImpedances(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
