/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.32                          *
 *        Compiled Oct  8 2015, 11:59:02                              *
 *        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
#include <GUI/WM_MyDefines.h>
#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_MULTIPAGE_0     (GUI_ID_USER + 0x01)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { FRAMEWIN_CreateIndirect, "MainWindow", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x0, 0 },
    { MULTIPAGE_CreateIndirect, "Multipage", ID_MULTIPAGE_0, 2, 2, 228, 295, 0, 0x0, 0 },
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
      //
      // Initialization of 'Multipage'
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0);
      MULTIPAGE_AddEmptyPage(hItem, hMP0, "Waveforms");
      MULTIPAGE_AddEmptyPage(hItem, hMP1, "Harmonics");
      MULTIPAGE_AddEmptyPage(hItem, hMP2, "Impedances");
      MULTIPAGE_AddEmptyPage(hItem, hMP3, "Settings");
      // USER START (Optionally insert additional code for further widget initialization)
      hMpage = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0);
      FRAMEWIN_SetClientColor(pMsg->hWin,GUI_LIGHTGRAY);
      // USER END
      break;
    case WM_NOTIFY_PARENT:
      Id    = WM_GetId(pMsg->hWinSrc);
      NCode = pMsg->Data.v;
      switch(Id) {
        case ID_MULTIPAGE_0: // Notifications sent by 'Multipage'
          switch(NCode) {
            case WM_NOTIFICATION_CLICKED:
              // USER START (Optionally insert code for reacting on notification message)
              // USER END
              break;
            case WM_NOTIFICATION_RELEASED:
              // USER START (Optionally insert code for reacting on notification message)
              // USER END
              break;
            case WM_NOTIFICATION_MOVED_OUT:
              // USER START (Optionally insert code for reacting on notification message)
              // USER END
              break;
            case WM_NOTIFICATION_VALUE_CHANGED:
              // USER START (Optionally insert code for reacting on notification message)
              // USER END
              break;
              // USER START (Optionally insert additional code for further notification handling)
              // USER END
          }
          break;
          // USER START (Optionally insert additional code for further Ids)
          // USER END
      }
      break;
      // USER START (Optionally insert additional message handling)
      // USER END
        default:
          WM_DefaultProc(pMsg);
          break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateMainWindow
 */
WM_HWIN CreateMainWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
