/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "WM_MyDefines.h"
#include "rtc.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_0    (GUI_ID_USER + 0x02)
#define ID_TEXT_1    (GUI_ID_USER + 0x03)
#define ID_SPINBOX_0    (GUI_ID_USER + 0x04)
#define ID_SPINBOX_1    (GUI_ID_USER + 0x05)
#define ID_BUTTON_1    (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Set date & time", ID_FRAMEWIN_0, 30, 40, 180, 240, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Hours", ID_TEXT_0, 30, 6, 37, 16, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_0, 98, 188, 50, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Minutes", ID_TEXT_1, 105, 6, 47, 17, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "HH", ID_SPINBOX_0, 20, 22, 50, 34, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect, "MM", ID_SPINBOX_1, 98, 22, 50, 34, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Cancel", ID_BUTTON_1, 20, 188, 50, 24, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  RTC_DateTypeDef sDate;
  RTC_TimeTypeDef sTime;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	    //
	    // Initialization of 'Set date & time'
	    //
		hItem = WM_GetDialogItem(pMsg->hWin, ID_FRAMEWIN_0);
		FRAMEWIN_SetClientColor(hItem,GUI_GRAY);
	    //
	    // Initialization of 'Spinbox HH'
	    //
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
		SPINBOX_SetRange(hItem,0,23);
		SPINBOX_SetValue(hItem,rtc_time.Hours);
		SPINBOX_SetButtonSize(hItem,24);
		SPINBOX_SetFont(hItem, GUI_FONT_16_1);
		hHH = hItem;
	    //
	    // Initialization of 'Spinbox MM'
	    //
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_1);
		SPINBOX_SetRange(hItem,0,59);
		SPINBOX_SetValue(hItem,rtc_time.Minutes);
		SPINBOX_SetButtonSize(hItem,24);
		SPINBOX_SetFont(hItem, GUI_FONT_16_1);
		hMM = hItem;
		break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'OK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)

    	  CALENDAR_GetSel(hCal,&EMWIN_date);

    	  /* RTC Update Date */
    	  sDate.WeekDay = RTC_WEEKDAY_MONDAY;
    	  sDate.Date = RTC_ByteToBcd2((uint8_t)EMWIN_date.Day);
    	  sDate.Month = RTC_ByteToBcd2((uint8_t)EMWIN_date.Month);
    	  sDate.Year = RTC_ByteToBcd2((uint8_t)(EMWIN_date.Year-2000));
    	  HAL_RTC_SetDate(&hrtc, &sDate, RTC_FORMAT_BCD);

    	  /* RTC Update Time */
    	  sTime.Hours = RTC_ByteToBcd2((uint8_t)SPINBOX_GetValue(hHH));
    	  sTime.Minutes = RTC_ByteToBcd2((uint8_t)SPINBOX_GetValue(hMM));
    	  sTime.Seconds = 0x0;
    	  sTime.SecondFraction = 0x0;
    	  sTime.DayLightSaving = RTC_DAYLIGHTSAVING_NONE;
    	  sTime.StoreOperation = RTC_STOREOPERATION_RESET;
    	  HAL_RTC_SetTime(&hrtc, &sTime, RTC_FORMAT_BCD);
    	  /* Close window */

    	  GUI_EndDialog(hDateTime,0);
    	  WM_EnableWindow(hMW);
    	  WM_EnableWindow(hMpage);
    	  hDateTime = 0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_0: // Notifications sent by 'HH'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_1: // Notifications sent by 'MM'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Cancel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
    	  GUI_EndDialog(hDateTime,0);
    	  WM_EnableWindow(hMW);
    	  WM_EnableWindow(hMpage);
    	  hDateTime = 0;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSet date & time
*/
WM_HWIN CreateSetDateTime(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
